all:
902:
	gcc eg.09.02.array-implementation-of-priority-queue.c -o eg.09.02.array-implementation-of-priority-queue.exe
	./eg.09.02.array-implementation-of-priority-queue.exe 10
903:
	gcc eg.09.03.bottomup-heapify.c -o eg.09.03.bottomup-heapify.exe
	./eg.09.03.bottomup-heapify.exe 10
