all: 902 903 906 907 909 9091 912 913
902:
	gcc eg.09.02.array-implementation-of-priority-queue.c -o eg.09.02.array-implementation-of-priority-queue.exe
	./eg.09.02.array-implementation-of-priority-queue.exe 10
903:
	gcc eg.09.03.bottomup-heapify.c -o eg.09.03.bottomup-heapify.exe
	./eg.09.03.bottomup-heapify.exe 10
906:
	gcc eg.09.06.sorting-with-a-priority-queue.c -o eg.09.06.sorting-with-a-priority-queue.exe
	./eg.09.06.sorting-with-a-priority-queue.exe 10
907:
	gcc eg.09.07.heapsort.c -o eg.09.07.heapsort.exe
	./eg.09.07.heapsort.exe 10
909:
	gcc eg.09.09.client.c eg.09.09.unordered-double-linked-list-priority-queue.c -o eg.09.09.client.exe
	./eg.09.09.client.exe 10 5
9091:
	gcc eg.09.09.unordered-double-linked-list-priority-queue.v1.c -o eg.09.09.unordered-double-linked-list-priority-queue.v1.exe
	./eg.09.09.unordered-double-linked-list-priority-queue.v1.exe 10 5
912:
	gcc eg.09.12.index-heap-based-priority-queue.c -o eg.09.12.index-heap-based-priority-queue.exe
	./eg.09.12.index-heap-based-priority-queue.exe 10
913:
	gcc eg.09.13.joining-two-equal-sized-power-of-2-heaps.c -o eg.09.13.joining-two-equal-sized-power-of-2-heaps.exe
	./eg.09.13.joining-two-equal-sized-power-of-2-heaps.exe 12 5
.PHONY:clean
clean:
	rm *.exe *.log
