u: users
a: AliyunDNS
c: AWS Cloudfront
e: AWS ELB
ef: AWS EFS
f1: cn-north-1a frontend server
f2: cn-north-1b frontend server
fm: frontend manager server
b1: cn-north-1a backend server
b2: cn-north-1b backend server
bm: backend manager server
d: AWS RDS database
r: AWS Redis server
m: AWS Middleware server
u -> a
a -> c
a -> e
e -> f1
e -> f2
e -> b1
e -> b2
e -> fm
e -> bm
ef -> f1
ef -> f2
ef -> b1
ef -> b2
ef -> fm
ef -> bm
c -> b1
c -> b2
b1 -> d
b2 -> d
bm -> d
b1 -> r
b2 -> r
bm -> r
bm <-> m
