u: Users
a: AliyunDNS
c: AWS Cloudfront
j: JD
t: Tmall
e: AWS ELB
w: AWS web servers
k: Jackyun
u -> a
u -> j
u -> t
a -> c
a -> e
j -> k
t -> k
c -> w
e -> w
k <-> w
WMS -> k
Kingdee <-> w
w -> AWS RDS
w -> AWS Redis
w -> AWS EFS
