u: Users
a: AliyunDNS
c: AWS Cloudfront
j: JD
t: Tmall
e: AWS ELB
w: AWS web servers {
  prod: {
    f1: cn-north-1a frontend
    f2: cn-north-1b frontend
    fm: frontend manager
    b1: cn-north-1a backend
    b2: cn-north-1b backend
    bm: backend manager
  }
  stage: {
    front2 frontend
    front2 backend
  }
  CMS
  Redmine
  m: Middleware
  Old Middleware
  Bastion
}
d: AWS RDS
k: Jackyun
u -> a
a -> c
a -> e
e -> w
c -> w.prod.b1
c -> w.prod.b2
w -> d
w -> AWS Redis
w -> AWS EFS
u -> j
u -> t
j -> k
t -> k
WMS -> k
k <-> w.m
Kingdee <-> w.m
Developers -> w.Bastion