u: users
a: AliyunDNS
c: AWS Cloudfront
j: JD
t: Tmall
e: AWS ELB
w: AWS web servers
d: AWS RDS
r: AWS Redis
k: Jackyun
u -> a
u -> j
u -> t
j -> k
t -> k
a -> c
a -> e
e -> w
c -> w
k <-> w
WMS -> k
Kingdee <-> w
w -> d
w -> r
w -> AWS EFS