u: users
a: AliyunDNS
c: AWS Cloudfront
j: JD
t: Tmall
e: AWS ELB
w: AWS web servers
d: AWS RDS database
m: AWS Middleware servers
k: Jackyun
u -> a
u -> j
u -> t
j -> k
t -> k
a -> c
a -> e
AWS EFS -> w
e -> w
c -> w
w -> d
w <-> m
k <-> m
WMS -> k
Kingdee <-> m
