all:601 602 603 604 605 606 6061 611 6111 613 6131 6132 614 616 617
601:
	gcc eg.06.01.example-of-array-sort-with-dirver-program.c -o eg.06.01.example-of-array-sort-with-dirver-program.exe
	./eg.06.01.example-of-array-sort-with-dirver-program.exe 10 1
#     ./eg.06.01.example-of-array-sort-with-dirver-program.exe 5 0
602:
	gcc eg.06.02.selection-sort.c -o eg.06.02.selection-sort.exe
	./eg.06.02.selection-sort.exe 10 1
#     ./eg.06.02.selection-sort.exe 5 0
603:
	gcc eg.06.03.insertion-sort.c -o eg.06.03.insertion-sort.exe
	./eg.06.03.insertion-sort.exe 10 1
604:
	gcc eg.06.04.bubble-sort.c -o eg.06.04.bubble-sort.exe
	./eg.06.04.bubble-sort.exe 10 1
605:
	gcc eg.06.05.shellsort.c -o eg.06.05.shellsort.exe
	./eg.06.05.shellsort.exe 10 1
606:
	gcc eg.06.06.sort-driver-for-arrays.c array.c ditem.c -o eg.06.06.sort-driver-for-arrays.exe
	./eg.06.06.sort-driver-for-arrays.exe 10 1
6061:
	gcc eg.06.06.sort-driver-for-arrays.v1.c -o eg.06.06.sort-driver-for-arrays.v1.exe
	./eg.06.06.sort-driver-for-arrays.v1.exe 10 1
611:
	gcc eg.06.11.sort-driver-for-string-item.c sarray.c sitem.c -o eg.06.11.sort-driver-for-string-item.exe
#     ./eg.06.11.sort-driver-for-string-item.exe 5
6111:
	gcc eg.06.11.sort-driver-for-string-item.v1.c -o eg.06.11.sort-driver-for-string-item.v1.exe
#     ./eg.06.11.sort-driver-for-string-item.v1.exe 5
613:
	gcc eg.06.13.sort-driver-for-record-items.c eg.06.13.data-type-implementation-for-record-items.c -o eg.06.13.exe
#     ./eg.06.13.exe 3
6131:
	gcc eg.06.13.sort-driver-for-record-items.v1.c -o eg.06.13.sort-driver-for-record-items.v1.exe
#     ./eg.06.13.sort-driver-for-record-items.v1.exe 3
6132:
	gcc eg.06.13.sort-driver-for-record-items.v2.c -o eg.06.13.sort-driver-for-record-items.v2.exe
#     ./eg.06.13.sort-driver-for-record-items.v2.exe 3
614:
	gcc eg.06.14.in-place-sort.c -o eg.06.14.in-place-sort.exe
	./eg.06.14.in-place-sort.exe
616:
	gcc eg.06.15.linked-list-client.c eg.06.16.linked-list-selection-sort.c -o eg.06.15.linked-list-client.exe
	./eg.06.15.linked-list-client.exe 5
617:
	gcc eg.06.17.key-indexed-counting.c -o eg.06.17.key-indexed-counting.exe
	./eg.06.17.key-indexed-counting.exe
.PHONY:clean
clean:
	rm *.exe
