all: 801 802 803 804 805 806 808
801:
	gcc eg.08.01.merging.c -o eg.08.01.merging.exe
	./eg.08.01.merging.exe
802:
	gcc eg.08.02.abstract-in-place-merge.c -o eg.08.02.abstract-in-place-merge.exe
	./eg.08.02.abstract-in-place-merge.exe
803:
	gcc eg.08.03.top-down-mergesort.c -o eg.08.03.top-down-mergesort.exe
	./eg.08.03.top-down-mergesort.exe 20 1
804:
	gcc eg.08.04.mergesort-without-copying.c -o eg.08.04.mergesort-without-copying.exe
	./eg.08.04.mergesort-without-copying.exe 20 1
805:
	gcc eg.08.05.buttomup-mergesort.c -o eg.08.05.buttomup-mergesort.exe
	./eg.08.05.buttomup-mergesort.exe 10 1
806:
	gcc eg.08.06.linked-list-merge.c -o eg.08.06.linked-list-merge.exe
	./eg.08.06.linked-list-merge.exe 20
808:
	gcc eg.08.08.bottomup-list-mergesort.c -o eg.08.08.bottomup-list-mergesort.exe
	./eg.08.08.bottomup-list-mergesort.exe 5
.PHONY:clean
clean:
	rm *.exe *.log
