521:
	gcc 5.21.c1.c 5.21.c2.c -o 5.21.exe
	./5.21.exe
521b:
	gcc 5.21.c1b.c 5.21.c2b.c -o 5.21b.exe
	./5.21b.exe
522:
	gcc 5.22.b1.c 5.22.b2.c -o 5.22.exe
	./5.22.exe
c84:
	gcc c84.c linkfunc.c -o c84.exe
	./c84.exe
c85:
	gcc delete.c letter.c display.c input.c -o c85.exe
	./c85.exe
c86:
	gcc record.c save_load.c add_disp.c delete_record.c -o c86.exe
	./c86.exe
## c87 doesn't work
c87:
	gcc student.c student_add_disp.c sav_load.c quee_remv_modi.c -o c87.exe
	./c87.exe
## c103 doesn't work
c103:
	gcc air.c airfight.c -o airfight.exe
	./airfight.exe
## c104 doesn't work
c104:
	gcc snake.c -o snake.exe
	./snake.exe
c105:
	gcc park1.c park.c -o park.exe
	./park.exe
.PHONY: clean
clean:
	rm -f *.exe *.log

