all: 301 302 3021 303 305 306 307 308 309
# all: eg.03.01.function-definition.exe eg.03.02.types-of-numbers.exe eg.03.02.types-of-numbers.v1.exe eg.03.03.point-data-type.exe eg.03.05.seive-of-eratosthenes.exe eg.03.06.dynamic-memory-allocation.exe eg.03.07.coin-flipping-simulation.exe eg.03.08.closest-point.exe eg.03.09.circular-list.exe
301:
	gcc eg.03.01.function-definition.c -o eg.03.01.function-definition.exe
302:
	gcc eg.03.02.types-of-numbers.c -o eg.03.02.types-of-numbers.exe
3021:
	gcc eg.03.02.types-of-numbers.v1.c int.c -o eg.03.02.types-of-numbers.v1.exe
303:
	gcc eg.03.03.point-data-type.c eg.03.04.point-type-implementation.c -o eg.03.03.point-data-type.exe
305:
	gcc eg.03.05.seive-of-eratosthenes.c -o eg.03.05.seive-of-eratosthenes.exe
306:
	gcc eg.03.06.dynamic-memory-allocation.c -o eg.03.06.dynamic-memory-allocation.exe
307:
	gcc eg.03.07.coin-flipping-simulation.c -o eg.03.07.coin-flipping-simulation.exe
308:
	gcc eg.03.08.closest-point.c eg.03.04.point-type-implementation.c -o eg.03.08.closest-point.exe
309:
	gcc eg.03.09.circular-list.c -o eg.03.09.circular-list.exe
	./eg.03.09.circular-list.exe 9 5
.PHONY : clean
clean :
	rm *.exe
