all: 301 302 3021 303 305 306 307 308 309 3091
# all: eg.03.01.function-definition.exe eg.03.02.types-of-numbers.exe eg.03.02.types-of-numbers.v1.exe eg.03.03.point-data-type.exe eg.03.05.seive-of-eratosthenes.exe eg.03.06.dynamic-memory-allocation.exe eg.03.07.coin-flipping-simulation.exe eg.03.08.closest-point.exe eg.03.09.circular-list.exe
301:
	gcc eg.03.01.function-definition.c -o eg.03.01.function-definition.exe
	./eg.03.01.function-definition.exe
302:
	gcc eg.03.02.types-of-numbers.c -o eg.03.02.types-of-numbers.exe
	./eg.03.02.types-of-numbers.exe 10
3021:
	gcc eg.03.02.types-of-numbers.v1.c int.c -o eg.03.02.types-of-numbers.v1.exe
	./eg.03.02.types-of-numbers.v1.exe 10
303:
	gcc eg.03.03.point-data-type.c eg.03.04.point-type-implementation.c -o eg.03.03.point-data-type.exe
	./eg.03.03.point-data-type.exe
305:
	gcc eg.03.05.seive-of-eratosthenes.c -o eg.03.05.seive-of-eratosthenes.exe
	./eg.03.05.seive-of-eratosthenes.exe
306:
	gcc eg.03.06.dynamic-memory-allocation.c -o eg.03.06.dynamic-memory-allocation.exe
	./eg.03.06.dynamic-memory-allocation.exe 1000
307:
	gcc eg.03.07.coin-flipping-simulation.c -o eg.03.07.coin-flipping-simulation.exe
	./eg.03.07.coin-flipping-simulation.exe 10 1000
308:
	gcc eg.03.08.closest-point.c eg.03.04.point-type-implementation.c -o eg.03.08.closest-point.exe
	./eg.03.08.closest-point.exe 1000 0.1
309:
	gcc eg.03.09.circular-list.c -o eg.03.09.circular-list.exe
	./eg.03.09.circular-list.exe 9 5
3091:
	gcc eg.03.09.circular-list.v1.c -o eg.03.09.circular-list.v1.exe
	./eg.03.09.circular-list.v1.exe 9 5
310:
	gcc eg.03.10.list-reversal.c -o eg.03.10.list-reversal.exe
	./eg.03.10.list-reversal.exe 5
3101:
	gcc eg.03.10.list-reversal.v1.c -o eg.03.10.list-reversal.v1.exe
	./eg.03.10.list-reversal.v1.exe
311:
	gcc eg.03.11.list-insertion-sort.c -o eg.03.11.list-insertion-sort.exe
	./eg.03.11.list-insertion-sort.exe 20
313:
	gcc eg.03.14.list-implementation.c eg.03.13.list-allocation.c -o eg.03.13.list-allocation.exe
	./eg.03.13.list-allocation.exe 9 5
315:
	gcc eg.03.15.string-search.c -o eg.03.15.string-search.exe
	./eg.03.15.string-search.exe 'hello world'
3151:
	gcc eg.03.15.string-search.v1.c -o eg.03.15.string-search.v1.exe
	./eg.03.15.string-search.v1.exe hello
316:
	gcc eg.03.16.two-dimensional-array-allocation.c -o eg.03.16.two-dimensional-array-allocation.exe
	./eg.03.16.two-dimensional-array-allocation.exe
317:
	gcc eg.03.17.sorting-an-array-of-strings.c -o eg.03.17.sorting-an-array-of-strings.exe
	./eg.03.17.sorting-an-array-of-strings.exe
318:
	gcc eg.03.18.adjacency-matrix-graph.c -o eg.03.18.adjacency-matrix-graph.exe
	./eg.03.18.adjacency-matrix-graph.exe
319:
	gcc eg.03.19.adjacency-lists-graph.c -o eg.03.19.adjacency-lists-graph.exe
	./eg.03.19.adjacency-lists-graph.exe
320:
	gcc eg.03.20.two-dimensional-array-of-lists.c eg.03.04.point-type-implementation.c -o eg.03.20.two-dimensional-array-of-lists.exe
	./eg.03.20.two-dimensional-array-of-lists.exe 10000 0.1
.PHONY : clean
clean :
	rm *.exe
