all:501 502 503 504 505 5051 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522
501:
	gcc eg.05.01.factorial-function.c -o eg.05.01.factorial-function.exe
	./eg.05.01.factorial-function.exe
502:
	gcc eg.05.02.a-questionable-recursive-program.c -o eg.05.02.a-questionable-recursive-program.exe
	./eg.05.02.a-questionable-recursive-program.exe
503:
	gcc eg.05.03.euclid-algorithms.c -o eg.05.03.euclid-algorithms.exe
	./eg.05.03.euclid-algorithms.exe
504:
	gcc eg.05.04.recursive-evaluation-of-prefix-expressions.c -o eg.05.04.recursive-evaluation-of-prefix-expressions.exe
	./eg.05.04.recursive-evaluation-of-prefix-expressions.exe '* + 7 * * 4 6 + 8 9 5'
505:
	gcc eg.05.05.recursive-functions-for-linked-lists.c item.c list.c -o eg.05.05.recursive-functions-for-linked-lists.exe
	./eg.05.05.recursive-functions-for-linked-lists.exe
5051:
	gcc eg.05.05.recursive-functions-for-linked-lists.v1.c -o eg.05.05.recursive-functions-for-linked-lists.v1.exe
	./eg.05.05.recursive-functions-for-linked-lists.v1.exe
506:
	gcc eg.05.06.divde-and-conquer-to-find-maximum.c -o eg.05.06.divde-and-conquer-to-find-maximum.exe
	./eg.05.06.divde-and-conquer-to-find-maximum.exe
507:
	gcc eg.05.07.solution-to-the-towers-of-hanoi.c -o eg.05.07.solution-to-the-towers-of-hanoi.exe
	./eg.05.07.solution-to-the-towers-of-hanoi.exe 5
508:
	gcc eg.05.08.divide-and-conquer-draw-ruler.c -o eg.05.08.divide-and-conquer-draw-ruler.exe
	./eg.05.08.divide-and-conquer-draw-ruler.exe
509:
	gcc eg.05.09.nonrecursive-draw-ruler.c -o eg.05.09.nonrecursive-draw-ruler.exe
	./eg.05.09.nonrecursive-draw-ruler.exe
510:
	gcc eg.05.10.fibonacci-numbers-recursive.c -o eg.05.10.fibonacci-numbers-recursive.exe
	./eg.05.10.fibonacci-numbers-recursive.exe
511:
	gcc eg.05.10.fibonacci-numbers-dynamic-programming.c -o eg.05.10.fibonacci-numbers-dynamic-programming.exe
	./eg.05.10.fibonacci-numbers-dynamic-programming.exe
512:
	gcc eg.05.12.knapsack-problem-recursive.c -o eg.05.12.knapsack-problem-recursive.exe
	./eg.05.12.knapsack-problem-recursive.exe
513:
	gcc eg.05.13.knapsack-problem-dynamic-programming.c -o eg.05.13.knapsack-problem-dynamic-programming.exe
	./eg.05.13.knapsack-problem-dynamic-programming.exe
514:
	gcc eg.05.14.recursive-tree-traversal.c -o eg.05.14.recursive-tree-traversal.exe
	./eg.05.14.recursive-tree-traversal.exe
515:
	gcc eg.05.15.preorder-traversal-nonrecursive.c -o eg.05.15.preorder-traversal-nonrecursive.exe
	./eg.05.15.preorder-traversal-nonrecursive.exe
516:
	gcc eg.05.16.level-order-traversal.c -o eg.05.16.level-order-traversal.exe
	./eg.05.16.level-order-traversal.exe
517:
	gcc eg.05.17.computation-of-tree-parameters.c -o eg.05.17.computation-of-tree-parameters.exe
	./eg.05.17.computation-of-tree-parameters.exe
518:
	gcc eg.05.18.quick-tree-print-function.c -o eg.05.18.quick-tree-print-function.exe
	./eg.05.18.quick-tree-print-function.exe
519:
	gcc eg.05.19.construction-of-a-tournament.c -o eg.05.19.construction-of-a-tournament.exe
	./eg.05.19.construction-of-a-tournament.exe
520:
	gcc eg.05.20.construction-of-a-parse-tree.c -o eg.05.20.construction-of-a-parse-tree.exe
	./eg.05.20.construction-of-a-parse-tree.exe
521:
	gcc eg.05.21.depth-first-search.c -o eg.05.21.depth-first-search.exe
	./eg.05.21.depth-first-search.exe
522:
	gcc eg.05.22.breadth-first-search.c -o eg.05.22.breadth-first-search.exe
	./eg.05.22.breadth-first-search.exe
.PHONY:clean
clean:
	rm *.exe
