all:
402:
	gcc eg_04_02_atof.c eg_04_02_getline.c eg_04_02_main.c -o eg_04_02.exe
	./eg_04_02.exe
403:
	gcc eg_04_03_getch.c eg_04_03_getop.c eg_04_03_main.c eg_04_03_stack.c -o eg_04_03.exe
	./eg_04_03.exe
502:
	gcc eg_04_03_getch.c eg_05_02_getint.c -o eg_05_02_getint.exe
	./eg_05_02_getint.exe
.PHONY: clean
clean:
	rm -f *.exe *.log
