all:
701:
	gcc eg.07.01.quicksort.c -o eg.07.01.quicksort.exe
	./eg.07.01.quicksort.exe 100 1
703:
	gcc eg.07.03.nonrecursive-quicksort.c -o eg.07.03.nonrecursive-quicksort.exe
	./eg.07.03.nonrecursive-quicksort.exe 100 1
704:
	gcc eg.07.04.improved-quicksort.c -o eg.07.04.improved-quicksort.exe
	./eg.07.04.improved-quicksort.exe 100 1
705:
	gcc eg.07.05.quicksort-with-three-way-partitioning.c -o eg.07.05.quicksort-with-three-way-partitioning.exe
	./eg.07.05.quicksort-with-three-way-partitioning.exe 100 1
706:
	gcc eg.07.06.selection.c -o eg.07.06.selection.exe
	./eg.07.06.selection.exe 10 1
707:
	gcc eg.07.07.nonrecursive-selection.c -o eg.07.07.nonrecursive-selection.exe
	./eg.07.07.nonrecursive-selection.exe 10 1
