all:
1301:
	gcc eg.13.01.balancing-a-bst.c -o eg.13.01.balancing-a-bst.exe
	./eg.13.01.balancing-a-bst.exe 10
1302:
	gcc eg.13.02.randomized-bst-insertion.c -o eg.13.02.randomized-bst-insertion.exe
	./eg.13.02.randomized-bst-insertion.exe 20
1303:
	gcc eg.13.03.randomized-bst-combination.c -o eg.13.03.randomized-bst-combination.exe
	./eg.13.03.randomized-bst-combination.exe 10
1304:
	gcc eg.13.04.deletion-in-a-randomized-bst.c -o eg.13.04.deletion-in-a-randomized-bst.exe
	./eg.13.04.deletion-in-a-randomized-bst.exe 10
1305:
	gcc eg.13.05.splay-insertion-in-bsts.c -o eg.13.05.splay-insertion-in-bsts.exe
	./eg.13.05.splay-insertion-in-bsts.exe 10
1306:
	gcc eg.13.06.insertion-in-red-black-bsts.c -o eg.13.06.insertion-in-red-black-bsts.exe
	./eg.13.06.insertion-in-red-black-bsts.exe 13
1307:
	gcc eg.13.07.skip-lists.c -o eg.13.07.skip-lists.exe
	./eg.13.07.skip-lists.exe 10
.PHONY: clean
clean:
	rm -f *.exe *.log
