all: 1401 1402 1403 1404 1405 1406 1407
1401:
	gcc eg.14.01.hash-function-for-string-keys.c -o eg.14.01.hash-function-for-string-keys.exe
	./eg.14.01.hash-function-for-string-keys.exe
1402:
	gcc eg.14.02.universal-hash-function.c -o eg.14.02.universal-hash-function.exe
	./eg.14.02.universal-hash-function.exe
1403:
	gcc eg.14.03.hashing-with-separate-chaining.c -o eg.14.03.hashing-with-separate-chaining.exe
	./eg.14.03.hashing-with-separate-chaining.exe 28
1404:
	gcc eg.14.04.linear-probing.c -o eg.14.04.linear-probing.exe
	./eg.14.04.linear-probing.exe 20
1405:
	gcc eg.14.05.deletion-in-a-linear-probing-hash-table.c -o eg.14.05.deletion-in-a-linear-probing-hash-table.exe
	./eg.14.05.deletion-in-a-linear-probing-hash-table.exe 20
1406:
	gcc eg.14.06.double-hashing.c -o eg.14.06.double-hashing.exe
	./eg.14.06.double-hashing.exe 20
1407:
	gcc eg.14.07.dynamic-hash-insertion.c -o eg.14.07.dynamic-hash-insertion.exe
	./eg.14.07.dynamic-hash-insertion.exe 26
.PHONY: clean
clean:
	rm -f *.exe *.log
