all: 1202 12021 1204 12041 1205 1206 1207 1209 1210 1211
1202:
	gcc eg.12.02.example-of-a-symbol-table-client.c item.c st.c -o eg.12.02.example-of-a-symbol-table-client.exe
	./eg.12.02.example-of-a-symbol-table-client.exe 10 1
12021:
	gcc eg.12.02.example-of-a-symbol-table-client.v1.c -o eg.12.02.example-of-a-symbol-table-client.v1.exe
	./eg.12.02.example-of-a-symbol-table-client.v1.exe 10 1
1204:
	gcc eg.12.04.array-based-symbol-table.c item.c client.c -o eg.12.04.array-based-symbol-table.exe
	./eg.12.04.array-based-symbol-table.exe 10 1
12041:
	gcc eg.12.04.array-based-symbol-table.v1.c -o eg.12.04.array-based-symbol-table.v1.exe
	./eg.12.04.array-based-symbol-table.v1.exe 20
1205:
	gcc eg.12.05.linked-list-based-symbol-table.c -o eg.12.05.linked-list-based-symbol-table.exe
	./eg.12.05.linked-list-based-symbol-table.exe 20
1206:
	gcc eg.12.06.binary-search.c -o eg.12.06.binary-search.exe
	./eg.12.06.binary-search.exe 20
1207:
	gcc eg.12.07.bst-based-symbol-table.c -o eg.12.07.bst-based-symbol-table.exe
	./eg.12.07.bst-based-symbol-table.exe 10
1209:
	gcc eg.12.09.insertion-in-bsts-nonrecursive.c -o eg.12.09.insertion-in-bsts-nonrecursive.exe
	./eg.12.09.insertion-in-bsts-nonrecursive.exe 20
1210:
	gcc eg.12.10.example-of-indexing-a-text-string.c -o eg.12.10.example-of-indexing-a-text-string.exe
	./eg.12.10.example-of-indexing-a-text-string.exe he.log
1211:
	gcc eg.12.11.rotations-in-bsts.c -o eg.12.11.rotations-in-bsts.exe
	./eg.12.11.rotations-in-bsts.exe 20
.PHONY: clean
clean:
	rm *.exe *.log
