all: 101 102 103 104
101:
	gcc eg.01.01.quick-find.c -o eg.01.01.quick-find.exe
	./eg.01.01.quick-find.exe
102:
	gcc eg.01.02.quick-union.c -o eg.01.02.quick-union.exe
	./eg.01.02.quick-union.exe
103:
	gcc eg.01.03.weighted-quick-union.c -o eg.01.03.weighted-quick-union.exe
	./eg.01.03.weighted-quick-union.exe
104:
	gcc eg.01.04.weighted-quick-union-with-halving.c -o eg.01.04.weighted-quick-union-with-halving.exe
	./eg.01.04.weighted-quick-union-with-halving.exe
.PHONY:clean
clean:
	rm -f *.exe *.log

