all: 201 202
201:
	gcc eg.02.01.sequential-search.c -o eg.02.01.sequential-search.exe
	./eg.02.01.sequential-search.exe
202:
	gcc eg.02.02.binary-search.c -o eg.02.02.binary-search.exe
	./eg.02.02.binary-search.exe
.PHONY:clean
clean:
	rm -f *.exe *.log
