all:
1501:
	gcc eg.15.01.binary-digital-search-tree.c -o eg.15.01.binary-digital-search-tree.exe
	./eg.15.01.binary-digital-search-tree.exe 20
1502:
	gcc eg.15.02.trie-search.c -o eg.15.02.trie-search.exe
	./eg.15.02.trie-search.exe 10
1503:
	gcc eg.15.03.trie-insertion.c -o eg.15.03.trie-insertion.exe
	./eg.15.03.trie-insertion.exe 10
1504:
	gcc eg.15.04.patricia-trie.c -o eg.15.04.patricia-trie.exe
	./eg.15.04.patricia-trie.exe
1507:
	gcc eg.15.07.existence-trie-search-and-insertion.c -o eg.15.07.existence-trie-search-and-insertion.exe
	./eg.15.07.existence-trie-search-and-insertion.exe
.PHONY: clean
clean:
	rm -f *.exe *.log
